### PR TITLE
Reattach HB Remote Api

### PR DESCRIPTION
**Pull request by alishahb**
Added functionality for reattach Honorbuddy

### CODE REVIEW

**Comment by alishahb** [comment]
Asking for merge this new functionality to main branch as huge used by GoldBoss users. To not have 2 separate version of HBRelog, which will need maintenance. 

It added new functionality:
Reattach HB to existing HBRelog task - for sake of switching users (restarting HB with new PID) and HBRelog recognize new HB PID as existing to continue execution.

**Comment by highvoltz** [comment]
Why do you need this functionality when HBRelog automatically restarts bot when bot process exits?

**Comment by alishahb** [comment]
GoldBoss do switch char without restarting WoW - it's not managed by hbrelog at this point, only HB got restarted, after new character loaded in world.

I need this because i do restart HB with custom command line parameters (which have no connection to HBRelog itself) and want it to recognize new instance of HB as same session (thats what for reattach is) that was and do not try to restart it (which it will try without this commit).

if it just quit and restart (HB) - hbrelog will consider its as new session and won't proceed current task as continue of same session (it will be new toon, so it wont recognize it and will try to restart wow, which people do not want).

People using my version of HBRelog a lot (basically most of GoldBoss users), but having separate version is hard as i need always to update it to the main branch, thats why i am asking to add this functionality to main branch.

**Comment by highvoltz** [comment]
Why are you launching HB with custom command line parameters?

> if it just quit and restart (HB) - hbrelog will consider its as new session and won't proceed current task as continue of same session (it will be new toon, so it wont recognize it and will try to restart wow, which people do not want).

Have you tried pausing the HBrelog profile before switching characters and resuming after character switch is complete?

**Comment by alishahb** [comment]
Yup, it will restart HB in any case (if it's not same instance - i.e. HB pid != what it was)

**Comment by AionLtd** [comment]
I believe such/similar functionality is very useful, when we schedule a huge list of WoW characters, if they belong to single WoW license.
Once each task is done, HBRelog would just logoff to character screen, then relog on the next character, without restarting WoW Client (This is the most common human behavior after all)
So it would not be useful for GoldBoss botbase only but for each community bot, running on schedules.

**Comment by florent46** [comment]
+1 for Added functionality for reattach  HBRelog for GoldBoss
thx

**Comment by alishahb** [comment]
Jadob, so can you merge it?

**Comment by qq1454055505** [comment]
For example, an account under 10 characters, whether you can add a new feature: from the first role to start a copy of the brush, brush off the line for the role of brush another number.

**Pull request closed without merging**
